[package]
name = "console-dioxus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shelter-fs = { path = "../shelter-fs", version = "0.1" }
dioxus = "0.4"
dioxus-web = "0.4"
dioxus-router = "0.4"
