on: [push, pull_request]

name: Lints
permissions:
  contents: read

# TODO[epic=ci]: lint commit, bash script, toml and yml files
jobs:
  lints:
    name: Lints (rustfmt, clippy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      # - name: Run cargo clippy on tests
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: --tests -- -D warnings