name: Security Audit
permissions:
  contents: read

on:
  push:
    # Check immediately if dependencies are altered
    paths:
      - '**/Cargo.toml'
      - 'Cargo.lock'
    # Check also at midnight each day
  schedule:
    - cron: '0 0 * * *'
      
jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}